services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  # api-gateway:
  #   build: ./api-gateway
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - rabbitmq
  # aggregator:
  #   build: ./aggregator
  #   depends_on:
  #     - rabbitmq
  # user-service:
  #   build: ./user-service
  #   depends_on:
  #     - rabbitmq
  # product-service:
  #   build: ./product-service
  #   depends_on:
  #     - rabbitmq
